version: '3.8'

services:
  web:
    container_name: deena_phone
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:password@13.228.30.99:5432/mydb?schema=public"
      NEXTAUTH_SECRET: "nextauthSecret"
      NEXTAUTH_URL: "http://13.228.30.99:3000/api/"
      BUCKET_NAME: "bucket-deenaphone"
      BUCKET_REGION: "ap-southeast-1"
      ACCESS_KEY: "AKIAXQIQATPPNLYIKO52"
      SECRET_ACCESS_KEY: "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"
    depends_on:
      - database

  database:
    image: postgres:latest
    container_name: deena_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
