version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:password@localhost:5432/mydb?schema=public"
      NEXTAUTH_SECRET : "nextauthSecret"
      NEXTAUTH_URL : 'http://52.77.242.119:3000/api/'

      #bucket name (S3)
      BUCKET_NAME : "bucket-deenaphone"

      #bucket region
      BUCKET_REGION : "ap-southeast-1"

      # access key ID (S3)
      ACCESS_KEY : "AKIAXQIQATPPNLYIKO52"

      # secret access key (S3)
      SECRET_ACCESS_KEY : "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"
    volumes:
      - pgdata:/var/lib/postgresql/data 
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 5432:5432
 
volumes:
  pgdata: